# Generated by Django 4.2 on 2025-05-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'managed': False, 'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
    ]
