# Generated by Django 4.2 on 2025-04-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CuponUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canjeado', models.BooleanField(default=False)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetBoutiqueApp.cupon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetBoutiqueApp.customuser')),
            ],
        ),
    ]
