# Generated by Django 4.2 on 2025-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0002_cupon_cuponusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.RenameField(
            model_name='cupon',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='url',
        ),
        migrations.AddField(
            model_name='cupon',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupon',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], default='porcentaje', max_length=20),
        ),
        migrations.AddField(
            model_name='cupon',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
