# Generated by Django 4.2 on 2025-06-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetBoutiqueApp', '0005_direccionusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DireccionUsuario',
        ),
    ]
